UoaWDCC/youth-of-orakei

- README.md
- test/readme.test.ts
i added my name to the readme.
> ORAKEI-7 add andrew to readme

- README.md
- test/readme.test.ts
- yarn.lock
Added Owen name to the README.md.
> ORAKEI-11 Added Owen in README.md

- README.md
- test/readme.test.ts
- yarn.lock
> ORAKEI-8 feat: Added Emmanuel Araba to the README

- src/pages/members.astro
- src/pages/posts/members.md
- src/scripts/getCovers.ts
- src/types/cover.ts
- src/types/page.ts
- Gets the covers from the database and returns them as an arrary with their names
- Created page and cover types
> Orakei 6 backend for get covers

- .vscode/settings.json
- src/pages/members.astro
- src/styles/members.css
finished adding photos + touch ups to the members page
> Orakei 32 finish adding images and descriptions in members page

- src/scripts/getMembers.ts
- src/types/memberRow.ts
- test/getMembers.test.ts
- vitest.config.js
Added getMembers Function & test for it.
> Orakei 4 create the backend for getting the list of members

- src/components/footer.astro
- src/pages/index.astro
- src/styles/footer.css
- src/styles/global.css
- src/styles/header.css
- src/styles/index.css
- nav + footer + index spacing and layout adjustments.
- general aesthetic modifications on some pages.
> Orakei 30 css refinements

- src/scripts/getMembers.ts
- src/styles/index.css
> fix: Added @tsIgnore to the rows, temporary fix

- src/scripts/getAnton.ts
- src/scripts/getDetails.ts
- yarn.lock
modified the existing function to now loop thru all blocks and get details for all the members
> Orakei 35 modify get anton to get details for generalisation 9.5

- src/components/ProjectTeam.tsx
- src/pages/members.astro
- src/styles/members.css
functioning but may not be the prettiest
> ORAKEI-72-Create-React-component-to-dynamically-change-project-members

- src/scripts/getMembers.ts
- src/types/memberRow.ts
- yarn.lock
Fixed the memberRow type and changed the getmembers function accordingly.
> FEAT: Fixed the getmembers function and the memberRow type.

- src/components/header.astro
> feat - Add homepage button

- src/scripts/getCovers.ts
- src/types/cover.ts
- test/getCovers.test.ts
Created tests to check that the function is returning something, and that there are covers with different types. Also updated cover type to add file attribute
> Wrote tests for get covers and updated cover type

- src/components/ProjectTeam.tsx
- src/pages/members.astro
- src/styles/global.css
- src/styles/members.css
done 👍 but the nav and footer are still not dynamic so may need to edit once those are done
> ORAKEI-76-Implement-Mobile-Members-Page

- src/pages/members.astro
- src/scripts/getTeamDescription.ts
- src/types/teamRow.ts
This function gets the name, tags and description attributes from the notion teams database and returns an array of that data. very epic.
> FEAT: getTeamDescriptions function and teamRow type.

- src/pages/contact.astro
When the user submits the form. The form's content gets emailed to YOO directly, epic.
> FEAT: added emailing feature to the contacts page.

- src/components/footer.astro
- src/styles/footer.css
Implemented Anna's footer and the mobile footer
> Feat Orakei-78-New-Footer-And-Mobile-Footer

- src/pages/contact.astro
Removed throw error when missing token. oops
> FEAT: Bugfixed the contacts page.

- src/scripts/fetchPageBlocks.ts
- src/scripts/getAnton.ts
- src/scripts/getDetails.ts
- src/scripts/getHomepageDescriptions.ts
Finished homepage descriptions function
> Orakei 80 add homepage descriptions to notion and retrieve it

- src/components/ProjectTeam.tsx
- src/pages/members.astro
- src/styles/members.css
- src/types/memberData.ts
The members page wasn't importing the ProjectTeam component as no types were being declared. I also passed projects down as a prop compared to calling the getMembers() function inside the component. Also fixed the <a> tag inside of the button as it didn't take full width of the button leading to nothing happening when the button was clicked.
> FEAT: Added types to the ProjectTeam component.

- yarn.lock
I added a yarn file very epic.
> FEAT: Added Yarn File

- src/components/projects page/PastProjectsList.tsx
- src/styles/index.css
Fixed issue with image carousel not displaying text properly too
> Changed text from cutout to on image.

- src/components/BlobBackground/BlobBackground.tsx
- src/components/BlobBackground/blobbackground.module.css
- src/pages/index.astro
- src/pages/projects.astro
BlobBackground is now a component.
- added BlobBackground to index, projects page.
See documentation on props within the component comments if you're curious on how to use it.
> added component blobs + fixed projects background

- src/components/Navbar/Navbar.tsx
- src/components/Navbar/nav.module.css
- src/components/index page/IndexGoalCard.tsx
- src/layouts/layout.astro
- src/pages/index.astro
- src/styles/global.css
`No information is available about this pull request.`
<sub><sup>[Contact GitHub Support.](https://support.github.com/request/landing)</sup></sub>
> Changed some code (details classified)

- src/styles/footer.css
Added footer media queries to improve mobile responsiveness.
- Reduced scale of footer elements (logo, text, etc) at all sizes.
- Flex directions change dynamically based on screen width.
> footer responsiveness improvements + reduced scaling

- .github/workflows/deploy.staging.yml
- Dockerfile
- src/pages/contact.astro
- src/scripts/getCovers.ts
- src/scripts/getDetails.ts
- src/scripts/getHomepageDescriptions.ts
- src/scripts/getHomepageImages.ts
- src/scripts/getMembers.ts
- src/scripts/getProjects.ts
- src/scripts/getTeamDescription.ts
I also added our missing env variables.
> FEAT: Added dockerfile and fly.staging configuration to allow for a staging branch.

- .github/workflows/deploy.staging.yml
- src/components/ImageCarousel.tsx
- src/pages/index.astro
- src/scripts/getCovers.ts
- src/scripts/getDetails.ts
- src/scripts/getHomepageDescriptions.ts
- src/scripts/getHomepageImages.ts
- src/scripts/getMembers.ts
- src/scripts/getPageDescriptions.ts
- src/scripts/getProjects.ts
- src/scripts/getTeamDescription.ts
you can now change the images, paragraphs, dates in the notion to display on the carousel, very epic 😎 . Also merged the changes from ORAKEI-staging so it stops giving us errors everytime we merge into main.
> FEAT: Integrated index carousel with the notion database.

- src/components/ImageCarousel.tsx
- src/components/TeamDisplayLeft.astro
- src/components/projects page/PastProjectsList.tsx
- src/pages/members.astro
- src/pages/projects.astro
- src/scripts/getHomepageDescriptions.ts
- src/scripts/getMembers.ts
- src/scripts/getPageDescriptions.ts
- src/scripts/getProjects.ts
- src/scripts/sortProjects.ts
- src/scripts/sortTeams.ts
- src/types/projectData.ts
- src/types/projectRow.ts
Project page integration to notion complete!
> ORAKEI-83-Display-projects-using-Notion-integration

- README.md
Added some nice badges representing our tech/documentation stack
> feat: added cool badges

- src/components/Navbar/Navbar.tsx
> Added archive link to navbar

- src/components/ImageCarousel.tsx
- src/components/projects page/PastProjectsList.tsx
- src/pages/projects.astro
- src/styles/index.css
- src/styles/projects.css
- made the projects page responsive
- mobile view now styled to have correct font size
- images are also all responsive
- only minor issue that remains is that the left and right arrows of the carousel do not align in the mobile version.
> ORAKEI-117-Mobile-projects-page-including-carousel

- src/components/Navbar/Navbar.tsx
- src/components/Navbar/nav.module.css
- src/pages/members.astro
- src/pages/projects.astro
- src/styles/members.css
i attempt to navigate the codebase to fix some styling issues
> Fix various styling quirks
